import { BONUS_CHARACTER, BONUS_WORD } from '../../constants';

export default {
  id: 'scrabble',
  name: 'Scrabble',
  allTilesBonusScore: 50,
  blankScore: 0,
  boardWidth: 15,
  boardHeight: 15,
  maximumNumberOfCharacters: 7,
  numberOfBlanks: 2,
  bonuses: [
    { x: 0, y: 0, type: BONUS_WORD, multiplier: 3 },
    { x: 3, y: 0, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 7, y: 0, type: BONUS_WORD, multiplier: 3 },
    { x: 11, y: 0, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 14, y: 0, type: BONUS_WORD, multiplier: 3 },
    { x: 1, y: 1, type: BONUS_WORD, multiplier: 2 },
    { x: 5, y: 1, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 9, y: 1, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 13, y: 1, type: BONUS_WORD, multiplier: 2 },
    { x: 2, y: 2, type: BONUS_WORD, multiplier: 2 },
    { x: 6, y: 2, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 8, y: 2, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 12, y: 2, type: BONUS_WORD, multiplier: 2 },
    { x: 0, y: 3, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 3, y: 3, type: BONUS_WORD, multiplier: 2 },
    { x: 7, y: 3, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 11, y: 3, type: BONUS_WORD, multiplier: 2 },
    { x: 14, y: 3, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 4, y: 4, type: BONUS_WORD, multiplier: 2 },
    { x: 10, y: 4, type: BONUS_WORD, multiplier: 2 },
    { x: 1, y: 5, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 5, y: 5, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 9, y: 5, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 13, y: 5, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 2, y: 6, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 6, y: 6, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 8, y: 6, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 12, y: 6, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 0, y: 7, type: BONUS_WORD, multiplier: 3 },
    { x: 3, y: 7, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 7, y: 7, type: BONUS_WORD, multiplier: 2 },
    { x: 11, y: 7, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 14, y: 7, type: BONUS_WORD, multiplier: 3 },
    { x: 2, y: 8, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 6, y: 8, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 8, y: 8, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 12, y: 8, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 1, y: 9, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 5, y: 9, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 9, y: 9, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 13, y: 9, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 4, y: 10, type: BONUS_WORD, multiplier: 2 },
    { x: 10, y: 10, type: BONUS_WORD, multiplier: 2 },
    { x: 0, y: 11, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 3, y: 11, type: BONUS_WORD, multiplier: 2 },
    { x: 7, y: 11, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 11, y: 11, type: BONUS_WORD, multiplier: 2 },
    { x: 14, y: 11, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 2, y: 12, type: BONUS_WORD, multiplier: 2 },
    { x: 6, y: 12, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 8, y: 12, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 12, y: 12, type: BONUS_WORD, multiplier: 2 },
    { x: 1, y: 13, type: BONUS_WORD, multiplier: 2 },
    { x: 5, y: 13, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 9, y: 13, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 13, y: 13, type: BONUS_WORD, multiplier: 2 },
    { x: 0, y: 14, type: BONUS_WORD, multiplier: 3 },
    { x: 3, y: 14, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 7, y: 14, type: BONUS_WORD, multiplier: 3 },
    { x: 11, y: 14, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 14, y: 14, type: BONUS_WORD, multiplier: 3 }
  ]
};
