/**
 * Covers side-effect imports of global stylesheets. Imports of *.module.scss
 * files resolve to their sibling .d.ts files, generated by
 * scripts/generate-scss-types.ts (run via the build, type-check, and dev scripts).
 */
declare module '*.scss' {}
