export { default as Board } from './Board';
export { default as Bonus } from './Bonus';
export { default as BonusValue } from './BonusValue';
export { default as Cell } from './Cell';
export { default as CharacterBonus } from './CharacterBonus';
// export { default as Config } from './Config';
export { default as HorizontalPattern } from './HorizontalPattern';
export { default as Pattern } from './Pattern';
export { default as Result } from './Result';
export { default as Tile } from './Tile';
export { default as VerticalPattern } from './VerticalPattern';
export { default as WordDefinition } from './WordDefinition';
export { default as WordBonus } from './WordBonus';
