import { BONUS_CHARACTER, BONUS_WORD } from '../constants';

export default {
  id: 'scrabble',
  name: 'Scrabble',
  boardWidth: 15,
  boardHeight: 15,
  maximumNumberOfCharacters: 7,
  minimumWordLength: 2,
  maximumWordLength: 15,
  blankScore: 0,
  allTilesBonusScore: 50,
  numberOfBlanks: 2,
  characters: [
    { character: 'a', score: 1, count: 9 },
    { character: 'ą', score: 5, count: 1 },
    { character: 'b', score: 3, count: 2 },
    { character: 'c', score: 2, count: 3 },
    { character: 'ć', score: 6, count: 1 },
    { character: 'd', score: 2, count: 3 },
    { character: 'e', score: 1, count: 7 },
    { character: 'ę', score: 5, count: 1 },
    { character: 'f', score: 5, count: 1 },
    { character: 'g', score: 3, count: 2 },
    { character: 'h', score: 3, count: 2 },
    { character: 'i', score: 1, count: 8 },
    { character: 'j', score: 3, count: 2 },
    { character: 'k', score: 2, count: 3 },
    { character: 'l', score: 2, count: 3 },
    { character: 'ł', score: 3, count: 2 },
    { character: 'm', score: 2, count: 3 },
    { character: 'n', score: 1, count: 5 },
    { character: 'ń', score: 7, count: 1 },
    { character: 'o', score: 1, count: 6 },
    { character: 'ó', score: 5, count: 1 },
    { character: 'p', score: 2, count: 3 },
    { character: 'r', score: 1, count: 4 },
    { character: 's', score: 1, count: 4 },
    { character: 'ś', score: 5, count: 1 },
    { character: 't', score: 2, count: 3 },
    { character: 'u', score: 3, count: 2 },
    { character: 'w', score: 1, count: 4 },
    { character: 'y', score: 2, count: 4 },
    { character: 'z', score: 1, count: 5 },
    { character: 'ź', score: 5, count: 1 },
    { character: 'ż', score: 9, count: 1 }
  ],
  bonuses: [
    { x: 0, y: 0, type: BONUS_WORD, multiplier: 3 },
    { x: 3, y: 0, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 7, y: 0, type: BONUS_WORD, multiplier: 3 },
    { x: 11, y: 0, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 14, y: 0, type: BONUS_WORD, multiplier: 3 },
    { x: 1, y: 1, type: BONUS_WORD, multiplier: 2 },
    { x: 5, y: 1, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 9, y: 1, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 13, y: 1, type: BONUS_WORD, multiplier: 2 },
    { x: 2, y: 2, type: BONUS_WORD, multiplier: 2 },
    { x: 6, y: 2, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 8, y: 2, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 12, y: 2, type: BONUS_WORD, multiplier: 2 },
    { x: 0, y: 3, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 3, y: 3, type: BONUS_WORD, multiplier: 2 },
    { x: 7, y: 3, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 11, y: 3, type: BONUS_WORD, multiplier: 2 },
    { x: 15, y: 3, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 4, y: 4, type: BONUS_WORD, multiplier: 2 },
    { x: 10, y: 4, type: BONUS_WORD, multiplier: 2 },
    { x: 1, y: 5, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 5, y: 5, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 9, y: 5, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 13, y: 5, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 2, y: 6, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 6, y: 6, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 8, y: 6, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 12, y: 6, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 0, y: 7, type: BONUS_WORD, multiplier: 3 },
    { x: 3, y: 7, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 7, y: 7, type: BONUS_WORD, multiplier: 2 },
    { x: 11, y: 7, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 14, y: 7, type: BONUS_WORD, multiplier: 3 },
    { x: 2, y: 8, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 6, y: 8, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 8, y: 8, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 12, y: 8, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 1, y: 9, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 5, y: 9, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 9, y: 9, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 13, y: 9, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 4, y: 10, type: BONUS_WORD, multiplier: 2 },
    { x: 10, y: 10, type: BONUS_WORD, multiplier: 2 },
    { x: 0, y: 11, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 3, y: 11, type: BONUS_WORD, multiplier: 2 },
    { x: 7, y: 11, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 11, y: 11, type: BONUS_WORD, multiplier: 2 },
    { x: 15, y: 11, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 2, y: 12, type: BONUS_WORD, multiplier: 2 },
    { x: 6, y: 12, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 8, y: 12, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 12, y: 12, type: BONUS_WORD, multiplier: 2 },
    { x: 1, y: 13, type: BONUS_WORD, multiplier: 2 },
    { x: 5, y: 13, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 9, y: 13, type: BONUS_CHARACTER, multiplier: 3 },
    { x: 13, y: 13, type: BONUS_WORD, multiplier: 2 },
    { x: 0, y: 14, type: BONUS_WORD, multiplier: 3 },
    { x: 3, y: 14, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 7, y: 14, type: BONUS_WORD, multiplier: 3 },
    { x: 11, y: 14, type: BONUS_CHARACTER, multiplier: 2 },
    { x: 14, y: 14, type: BONUS_WORD, multiplier: 3 }
  ]
};
