//FIXME scores are based on persian scrabble wiki but the counts are made up, we know total should be 100

const tilesFa = [
  { character: 'ا', count: 5, score: 1 },
  { character: 'ب', count: 5, score: 1 },
  { character: 'پ', count: 5, score: 6 },
  { character: 'ت', count: 5, score: 1 },
  { character: 'ث', count: 1, score: 10 },
  { character: 'ج', count: 3, score: 5 },
  { character: 'چ', count: 3, score: 6 },
  { character: 'ح', count: 3, score: 6 },
  { character: 'خ', count: 3, score: 5 },
  { character: 'د', count: 5, score: 1 },
  { character: 'ذ', count: 1, score: 10 },
  { character: 'ر', count: 5, score: 1 },
  { character: 'ز', count: 3, score: 4 },
  { character: 'ژ', count: 1, score: 10 },
  { character: 'س', count: 4, score: 2 },
  { character: 'ش', count: 3, score: 3 },
  { character: 'ص', count: 3, score: 6 },
  { character: 'ض', count: 2, score: 8 },
  { character: 'ط', count: 2, score: 8 },
  { character: 'ظ', count: 1, score: 10 },
  { character: 'ع', count: 3, score: 5 },
  { character: 'غ', count: 2, score: 8 },
  { character: 'ف', count: 3, score: 4 },
  { character: 'ق', count: 3, score: 5 },
  { character: 'ک', count: 3, score: 3 },
  { character: 'گ', count: 3, score: 4 },
  { character: 'ل', count: 4, score: 2 },
  { character: 'م', count: 5, score: 1 },
  { character: 'ن', count: 5, score: 1 },
  { character: 'و', count: 5, score: 1 },
  { character: 'ه', count: 5, score: 1 },
  { character: 'ی', count: 5, score: 1 },
];

export default tilesFa;
