name: bunx

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * *' # every day at 00:00 UTC
  workflow_dispatch: # allow manual triggering

jobs:
  bunx:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run build
      - uses: cypress-io/github-action@v7
        with:
          install: false
          build: bun add --global scrabble-solver@latest
          start: scrabble-solver
          wait-on: 'http://localhost:3333'
        env:
          CYPRESS_BASE_URL: http://localhost:3333
      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
